import json
from pathlib import Path
from .models import Project, Scene


def _scene_payload(scene: Scene) -> dict:
    return scene.model_dump()


def blender_script(project: Project) -> str:
    """Compatibility exporter: builds the first scene as an animated preview."""
    if not project.scenes:
        return '# Book3D Studio: project has no scenes\n'
    return blender_scene_script(project, project.scenes[0], "preview.mp4")


def blender_scene_script(project: Project, scene: Scene, output_path: str) -> str:
    payload = json.dumps(_scene_payload(scene), ensure_ascii=False)
    characters = [c.name for c in project.characters]
    return f'''# Generated by Book3D Studio v0.4.1
# This is a procedural PREVIEW scene. AI-generated production assets replace
# these placeholders in later pipeline stages.
import bpy, math, json, os
from mathutils import Vector

PROJECT_TITLE = {project.title!r}
STYLE = {project.style!r}
SCENE = json.loads({json.dumps(payload)})
KNOWN_CHARACTERS = {characters!r}
OUTPUT = {str(output_path)!r}
PROFILE = os.environ.get('BOOK3D_RENDER_PROFILE','quality').strip().lower()
PROFILES = {{
    'fast':    {{'fps': 15, 'w': 854,  'h': 480,  'max_seconds': 8.0,  'crf': 'MEDIUM'}},
    'quality': {{'fps': 24, 'w': 1280, 'h': 720,  'max_seconds': 15.0, 'crf': 'HIGH'}},
    'main':    {{'fps': 24, 'w': 1920, 'h': 1080, 'max_seconds': 0.0, 'crf': 'PERC_LOSSLESS'}},
}}
CFG = PROFILES.get(PROFILE, PROFILES['quality'])
FPS = CFG['fps']


def reset():
    bpy.ops.object.select_all(action='SELECT')
    bpy.ops.object.delete(use_global=False)
    for datablocks in (bpy.data.meshes, bpy.data.curves, bpy.data.materials, bpy.data.cameras, bpy.data.lights):
        pass


def mat(name, rgba, metallic=0.0, roughness=0.55):
    m = bpy.data.materials.get(name) or bpy.data.materials.new(name)
    m.diffuse_color = rgba
    m.metallic = metallic
    m.roughness = roughness
    return m


def apply_mat(obj, material):
    if len(obj.data.materials): obj.data.materials[0] = material
    else: obj.data.materials.append(material)


def add_floor():
    bpy.ops.mesh.primitive_plane_add(size=24, location=(0,0,0))
    floor = bpy.context.object
    floor.name = 'ENV_Floor'
    apply_mat(floor, mat('Floor',(0.08,0.09,0.12,1), metallic=0.05, roughness=0.7))
    bpy.ops.mesh.primitive_cube_add(location=(0,4.5,2.5), scale=(7,0.15,2.5))
    wall = bpy.context.object
    wall.name = 'ENV_BackWall'
    apply_mat(wall, mat('Wall',(0.13,0.15,0.19,1), metallic=0.1, roughness=0.6))


def add_person(name, loc, idx):
    x,y,z = loc
    bpy.ops.mesh.primitive_cylinder_add(vertices=24, radius=0.36, depth=1.25, location=(x,y,z+1.0))
    body = bpy.context.object
    body.name = 'CHAR_'+name.replace(' ','_')
    palette = [
        (0.20,0.38,0.62,1),(0.56,0.25,0.24,1),(0.26,0.48,0.31,1),
        (0.48,0.34,0.58,1),(0.58,0.48,0.20,1),(0.20,0.50,0.52,1)
    ]
    apply_mat(body, mat('CharMat_'+str(idx), palette[idx%len(palette)], roughness=0.45))
    bpy.ops.mesh.primitive_uv_sphere_add(segments=24, ring_count=12, radius=0.31, location=(x,y,z+1.82))
    head = bpy.context.object
    head.name = body.name+'_Head'
    apply_mat(head, mat('Skin_'+str(idx),(0.48+0.04*(idx%4),0.31+0.03*(idx%3),0.22+0.02*(idx%2),1),roughness=0.55))
    head.parent = body
    head.matrix_parent_inverse = body.matrix_world.inverted()
    return body


def add_camera():
    bpy.ops.object.camera_add(location=(0,-8.5,3.0))
    cam = bpy.context.object
    cam.name = 'CAM_Main'
    cam.data.lens = 45
    bpy.context.scene.camera = cam
    return cam


def point_camera(cam, point):
    direction = Vector(point) - cam.location
    cam.rotation_euler = direction.to_track_quat('-Z','Y').to_euler()


def add_lights():
    bpy.ops.object.light_add(type='AREA', location=(3,-3,6))
    key=bpy.context.object; key.name='LIGHT_Key'; key.data.energy=900; key.data.shape='DISK'; key.data.size=5
    key.rotation_euler=(math.radians(18),0,math.radians(35))
    bpy.ops.object.light_add(type='AREA', location=(-4,-1,3.5))
    fill=bpy.context.object; fill.name='LIGHT_Fill'; fill.data.energy=450; fill.data.size=4
    fill.rotation_euler=(math.radians(65),0,math.radians(-55))
    bpy.ops.object.light_add(type='AREA', location=(0,4,5))
    rim=bpy.context.object; rim.name='LIGHT_Rim'; rim.data.energy=700; rim.data.size=3
    rim.rotation_euler=(math.radians(-25),0,math.radians(180))


def animate(scene, cam, actors):
    shots = scene.get('shots') or []
    if not shots:
        shots=[{{'duration_s':5,'shot_type':'wide','camera_move':'slow push-in','action':scene.get('summary','')}}]
    frame=1
    max_total=float(CFG['max_seconds'])
    elapsed=0.0
    for si,shot in enumerate(shots):
        planned=float(shot.get('duration_s',5.0))
        dur = planned if PROFILE in ('quality','main') else min(planned,3.0)
        if max_total>0 and elapsed+dur>max_total: dur=max(1.0,max_total-elapsed)
        start=frame; end=frame+max(1,int(dur*FPS))
        st=str(shot.get('shot_type','')).lower()
        if 'close' in st:
            base=(1.2 if si%2 else -1.2,-4.4,2.15); lens=62
        elif 'medium' in st or 'over' in st:
            base=(-1.5 if si%2 else 1.5,-5.8,2.45); lens=52
        else:
            base=(0,-8.0,3.1); lens=40
        cam.location=base; cam.data.lens=lens; point_camera(cam,(0,0.5,1.35)); cam.keyframe_insert('location',frame=start); cam.keyframe_insert('rotation_euler',frame=start); cam.data.keyframe_insert('lens',frame=start)
        move=str(shot.get('camera_move','')).lower()
        if 'push' in move or 'dolly' in move:
            cam.location.y += 1.1
        elif 'orbit' in move:
            cam.location.x += 1.5 if si%2==0 else -1.5
        elif 'handheld' in move:
            cam.location.x += 0.18; cam.location.z += 0.08
        point_camera(cam,(0,0.5,1.35)); cam.keyframe_insert('location',frame=end); cam.keyframe_insert('rotation_euler',frame=end)
        for ai,a in enumerate(actors):
            a.keyframe_insert('location',frame=start)
            a.location.x += (0.10 if (ai+si)%2==0 else -0.10)
            a.location.y += 0.08*((si%3)-1)
            a.keyframe_insert('location',frame=end)
        frame=end+1; elapsed+=dur
        if max_total>0 and elapsed>=max_total: break
    bpy.context.scene.frame_start=1
    bpy.context.scene.frame_end=max(2,frame-1)


reset()
add_floor(); add_lights(); cam=add_camera()
scene_chars = SCENE.get('characters') or KNOWN_CHARACTERS[:3]
scene_chars = scene_chars[:6]
actors=[]
positions=[(-1.6,0.4,0),(0,0.6,0),(1.6,0.4,0),(-2.4,1.7,0),(0,1.9,0),(2.4,1.7,0)]
for i,name in enumerate(scene_chars): actors.append(add_person(name,positions[i],i))
animate(SCENE,cam,actors)

sc=bpy.context.scene
_selected_engine = None
_forced_engine = os.environ.get('BOOK3D_RENDER_ENGINE','').strip()
_engine_candidates = []
if _forced_engine:
    _engine_candidates.append(_forced_engine)
for _engine in ('BLENDER_EEVEE_NEXT', 'BLENDER_EEVEE', 'BLENDER_WORKBENCH', 'CYCLES'):
    if _engine not in _engine_candidates:
        _engine_candidates.append(_engine)
for _engine in _engine_candidates:
    try:
        sc.render.engine = _engine
        _selected_engine = _engine
        break
    except (TypeError, ValueError):
        pass
if _selected_engine is None:
    raise RuntimeError('No supported Blender render engine was found.')
print('Book3D render engine:', _selected_engine)
if _selected_engine == 'BLENDER_WORKBENCH':
    try:
        sc.display.shading.light = 'STUDIO'
        sc.display.shading.show_shadows = PROFILE != 'fast'
        sc.display.shading.show_cavity = PROFILE != 'fast'
        sc.display.shading.cavity_type = 'BOTH'
        sc.display.shading.show_specular_highlight = PROFILE != 'fast'
        sc.display.shading.show_object_outline = PROFILE != 'fast'
        print('Book3D Workbench profile:', PROFILE)
    except Exception as _e:
        print('BOOK3D_WORKBENCH_TUNING_WARNING', repr(_e))
elif _selected_engine == 'CYCLES':
    try:
        sc.cycles.device = 'CPU'
        sc.cycles.samples = 4
        sc.cycles.use_denoising = False
        print('Book3D Cycles device: CPU, samples: 4')
    except Exception as _e:
        print('BOOK3D_CYCLES_CPU_WARNING', repr(_e))
sc.render.resolution_x=int(CFG['w'])
sc.render.resolution_y=int(CFG['h'])
sc.render.resolution_percentage=100
sc.render.fps=FPS
_img = sc.render.image_settings
if hasattr(_img, 'media_type'):
    try:
        _img.media_type = 'VIDEO'
        print('Book3D output media type: VIDEO')
    except (TypeError, ValueError) as _e:
        print('BOOK3D_MEDIA_TYPE_WARNING', repr(_e))
try:
    _img.file_format = 'FFMPEG'
    print('Book3D output format: FFMPEG')
except (TypeError, ValueError) as _e:
    if not (hasattr(_img, 'media_type') and getattr(_img, 'media_type', None) == 'VIDEO'):
        raise
    print('BOOK3D_FILE_FORMAT_INFO', repr(_e))

sc.render.ffmpeg.format='MPEG4'
sc.render.ffmpeg.codec='H264'
sc.render.ffmpeg.constant_rate_factor=CFG['crf']
try:
    sc.render.ffmpeg.ffmpeg_preset='GOOD'
except (TypeError, ValueError, AttributeError):
    pass
_output_stem=os.path.splitext(OUTPUT)[0]
sc.render.filepath=_output_stem
sc.render.use_file_extension=True
sc.world.color=(0.015,0.02,0.035)
sc['book3d_project']=PROJECT_TITLE
sc['book3d_scene_id']=SCENE.get('id','')
sc['book3d_location']=SCENE.get('location','')
sc['book3d_render_profile']=PROFILE
print('Book3D profile:', PROFILE, CFG['w'], 'x', CFG['h'], '@', FPS, 'fps')

blend_path=os.path.splitext(OUTPUT)[0]+'.blend'
bpy.ops.wm.save_as_mainfile(filepath=blend_path)
bpy.ops.render.render(animation=True)
_render_dir=os.path.dirname(OUTPUT)
_candidates=[
    OUTPUT,
    _output_stem+'.mp4',
    _output_stem+'.MP4',
]
for _name in os.listdir(_render_dir):
    _p=os.path.join(_render_dir,_name)
    if _name.lower().endswith('.mp4') and _p not in _candidates:
        _candidates.append(_p)
_actual=next((_p for _p in _candidates if os.path.isfile(_p) and os.path.getsize(_p)>0),None)
if _actual and os.path.abspath(_actual)!=os.path.abspath(OUTPUT):
    try:
        if os.path.exists(OUTPUT): os.remove(OUTPUT)
        os.replace(_actual,OUTPUT)
    except Exception as _e:
        print('BOOK3D_NORMALIZE_WARNING',repr(_e))
print('BOOK3D_RENDER_COMPLETE', OUTPUT, 'exists=', os.path.exists(OUTPUT), 'bytes=', os.path.getsize(OUTPUT) if os.path.exists(OUTPUT) else 0)
'''
